// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  ai_disclosure: dynamic(() => import("./AiDisclosure")),
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  inter_link: dynamic(() => import("./InterLink")),
  scroll_down_indicator: dynamic(() => import("./ScrollDownIndicator")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  titles: dynamic(() => import("./Titles")),
  video_link: dynamic(() => import("./VideoLink")),
};
